const express = require('express');

const { auth } = require('../../middlewares/auth');
const { projectController } = require("../../controllers");
const { projectValidation } = require('../../validations');
const router = express.Router();

router.route('/get-projects').get(auth('getProject'),projectController.getProject);
router.route('/get-all-archived-projects').get(auth('getAllArchivedProject'),projectController.getAllArchivedProject);
router.route('/get-user-project/:userId').get(auth('getUserProject'),projectController.getUserProject);
router.route('/get-user-project-admin/:userId').get(auth('getUserProject'),projectController.getUserProjectforAdmin);
router.route('/add-project').post(auth('addProject'), projectController.addProject);
router.route('/edit-project-details/:projectId').patch(auth('updateProject'), projectController.editProjectDetails);
router.route('/delete-project-recipients/:projectId').delete(auth('updateProject'), projectController.deleteProjectRecipients);
router.route('/archive-project/:projectId').patch(auth('archiveProject'), projectController.archiveProject);
router.route('/get-project-detail/:projectId').get(auth('getProjectDetails'),projectController.getProjectDetails);
router.route('/project-update/:projectId').post(auth('projectUpdates'),projectController.projectUpdates);
router.route('/create-new/project-subject/:projectId').post(auth('AddNewProjectSubject'),projectController.AddNewProjectSubject);
router.route('/get-project-update-status-detail/:projectId').get(auth('getProjectUpdateStatusDetails'),projectController.getProjectUpdateStatusDetails);
router.route('/get-project/subjects-by-id/:projectId').get(auth('getProjectSubjectsByProjectId'),projectController.getProjectSubjectsByProjectId);
router.route('/get-project-update-detail/:projectId').get(auth('getProjectUpdateDetails'),projectController.getProjectUpdateDetails);
router.route('/update-message/:messageId').put(auth('updateMessage'),projectController.updateMessage);
router.route('/update/project-message/:projectMessageId').put(auth('updateProjectMessage'),projectController.updateProjectMessage);
router.route('/get-daily-status').get(auth('getDailyStatus'),projectController.getDailyStatus);
router.route('/get-sales-status').get(auth('getSalesStatus'),projectController.getSalesStatus);
router.route('/get-daily-status/:userId').get(auth('getDailyStatusById'),projectController.getDailyStatusById);
router.route('/get-general-project-statuses/:userId').get(auth('getGeneralStatusById'),projectController.getGeneralStatusById);
router.route('/get-general-project-statuses-user/:userId').get(auth('getGeneralStatusOfSingleUser'),projectController.getGeneralStatusOfSingleUser);
router.route('/get-project-updates/:userId').get(auth('getProjectUpdatesById'),projectController.getProjectUpdatesById);
router.route('/add-daily-status').post(auth('addDailyStatus'), projectController.addDailyStatus);
router.route('/add-daily-status_in/project_update').post(auth('addDailyStatusInProjectUpdate'), projectController.addDailyStatusInProjectUpdate);
router.route('/send-mail-to-tagged-users').post(projectController.sendMailToTaggedUsers);
router.route('/get-subject-details/:subjectId').get(auth('getSubjectDetails'), projectController.getSubjectDetails);
router.route('/get-project/updated-details/:projectId').get(auth('getProjectUpdatedDetails'), projectController.getProjectUpdatedDetails);
router.route('/delete-message/:messageId').delete(auth('deleteMessage'), projectController.deleteMessage);
router.route('/delete/project-message/:projectMessageId').delete(auth('deleteProjectMessage'), projectController.deleteProjectMessage);
router.route('/get-team-profile-images').get(auth('getTeamProfileImages'),projectController.getTeamProfileImages);
router.route('/get-status-detail').get(auth('getStatusDetailById'),projectController.getStatusDetailById);
router.route('/get-sales-team-profile-images').get(auth('getSalesTeamProfileImages'),projectController.getSalesTeamProfileImages);
router.route('/get-sales-updates-by-recipients').get(auth('salesUpdaytesByRecipients'),projectController.salesUpdaytesByRecipients);
router.route('/get-all-employees-sales-updates').get(auth('getAllEmployeesForSalesUpdate'), projectController.getAllEmployeesForSalesUpdate);
module.exports = router;